version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: node_boilerplate_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: node_app
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: node_boilerplate_redis
    ports:
      - '6379:6379'
    networks:
      - app-network

  app:
    build: .
    container_name: node_boilerplate_app
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/node_app
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - app-network
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
